// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createRow = `-- name: CreateRow :exec
INSERT INTO notes (name, val, month, year)
VALUES (?, ?, ?, ?)
`

type CreateRowParams struct {
	Name  string
	Val   int64
	Month int64
	Year  int64
}

func (q *Queries) CreateRow(ctx context.Context, arg CreateRowParams) error {
	_, err := q.db.ExecContext(ctx, createRow,
		arg.Name,
		arg.Val,
		arg.Month,
		arg.Year,
	)
	return err
}

const getAvg = `-- name: GetAvg :one
SELECT AVG(val) FROM notes
WHERE name = ? AND month = ? AND year = ?
`

type GetAvgParams struct {
	Name  string
	Month int64
	Year  int64
}

func (q *Queries) GetAvg(ctx context.Context, arg GetAvgParams) (sql.NullFloat64, error) {
	row := q.db.QueryRowContext(ctx, getAvg, arg.Name, arg.Month, arg.Year)
	var avg sql.NullFloat64
	err := row.Scan(&avg)
	return avg, err
}
